# This wqorkflow runs visual tests every time 
name: Run visual tests
on:
  push:
    paths:
      - 'src/**'
jobs:
  start-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Start Storybook
        run: yarn start &
      - name: Run Visual Regression test
        run: yarn test:creevey
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: tests/report/
